# Generated by Django 3.2.4 on 2021-06-07 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_rename_userid_bug_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='username',
            new_name='user',
        ),
    ]
